name: Python CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install xlsxwriter
        pip install numpy
        pip install pyGitHub
    - name: Run Script
      env : 
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python githubtags.py
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: repos
        path: repos.xlsx